### ISSUE TITLE
Make completion debugger handle list output

### ISSUE THREAD

**Issue by jmbhughes** [punch-mission/punchbowl#303]
If it's not just a single NDCube we have problems:

```
An error was encountered while running hook 'completion_debugger'
Traceback (most recent call last):
  File "/home/marcus.hughes/build4/venv/lib64/python3.11/site-packages/prefect/task_engine.py", line 337, in call_hooks
    result = hook(task, task_run, state)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/marcus.hughes/build4/venv/lib64/python3.11/site-packages/punchbowl/prefect.py", line 14, in completion_debugger
    new_filename = f"{get_base_file_name(cube)}_{task.name}.fits"
                      ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/marcus.hughes/build4/venv/lib64/python3.11/site-packages/punchbowl/data/io.py", line 33, in get_base_file_name
    obscode = cube.meta["OBSCODE"].value
              ^^^^^^^^^
AttributeError: 'list' object has no attribute 'meta'
```

**Comment by jmbhughes** [comment]
This was done.
